name: Deploy to Heroku

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: create env file
        env:
          PORT: ${{ secrets.APP_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASS: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.APP_DB_NAME }}
          SECRET_JWT: ${{ secrets.JWT_SECRET }}
        run: |
          touch .env
          echo PORT=$APP_PORT >> .env
          echo DB_HOST=$DB_HOST >> .env
          echo DB_USERNAME=$DB_USERNAME >> .env
          echo DB_PASSWORD=$DB_PASSWORD >> .env
          echo DB_PORT=$DB_PORT >> .env
          echo DB_NAME=$DB_NAME >> .env
          echo JWT_SECRET=$JWT_SECRET >> .env

      - name: Build and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v3.1.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: './docker/go/'
          process_type: 'web'